# Generated by Django 2.2 on 2019-05-06 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_code', models.PositiveIntegerField(blank=True, help_text='The three digit code referring to the contruction type.', null=True, verbose_name='stat_code')),
                ('date_issued', models.DateTimeField(help_text='When the permit was issued.', verbose_name='date issued')),
                ('permit_code', models.CharField(blank=True, default='', help_text='The alphabetic code that distinguishes different construction classes, eg commercial or residential.', max_length=20, verbose_name='permit code')),
                ('permit_number', models.CharField(blank=True, default='', help_text='The permit number used to idential records.', max_length=225, verbose_name='permit number')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='The latitude of the permit location', max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='The longitude of the permit location', max_digits=9, null=True, verbose_name='longitude')),
                ('address', models.CharField(blank=True, default='', help_text='The primary address provided.', max_length=255, verbose_name='address')),
                ('address2', models.CharField(blank=True, default='', help_text='The second line of address, if provided.', max_length=255, verbose_name='address2')),
                ('construction_type', models.CharField(blank=True, default='', help_text='The type of construction allowed by this permit.', max_length=255, verbose_name='construction type')),
                ('units', models.PositiveIntegerField(blank=True, default=0, help_text='.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='units')),
                ('valuation', models.PositiveIntegerField(blank=True, default=0, help_text='.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valuation')),
                ('fee', models.PositiveIntegerField(blank=True, default=0, help_text='.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fee')),
                ('owner', models.CharField(blank=True, default='', help_text='.', max_length=255, verbose_name='owner')),
                ('contractor', models.CharField(blank=True, default='', help_text='.', max_length=255, verbose_name='contractor')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='The date and time this permit was created.', verbose_name='created at')),
            ],
        ),
    ]
